spring:
  application:
    name: showpet

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import:
      - s3bucket.yaml
      - mysql.yaml

  enabled:
    anon: true