spring:
  application:
    name: showpet
  config:
    import:
      - s3bucket.yaml
      - application-security.yaml

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    # https://kukim.tistory.com/105
    url: jdbc:h2:mem:showpet
    username: sa
    password: ''

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
